-- MySQL Script generated by MySQL Workbench
-- Thu Apr 20 19:59:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema almoxarifado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema almoxarifado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `almoxarifado` DEFAULT CHARACTER SET utf8 ;
USE `almoxarifado` ;

-- -----------------------------------------------------
-- Table `almoxarifado`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifado`.`Produto` (
  `idProduto` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almoxarifado`.`Almoxarifado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifado`.`Almoxarifado` (
  `idAlmoxarifado` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAlmoxarifado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almoxarifado`.`Saldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almoxarifado`.`Saldo` (
  `idSaldo` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Almoxarifado_idAlmoxarifado` INT NOT NULL,
  PRIMARY KEY (`idSaldo`, `Produto_idProduto`, `Almoxarifado_idAlmoxarifado`),
  INDEX `fk_Saldo_Produto_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Saldo_Almoxarifado1_idx` (`Almoxarifado_idAlmoxarifado` ASC) VISIBLE,
  CONSTRAINT `fk_Saldo_Produto`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `almoxarifado`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Saldo_Almoxarifado1`
    FOREIGN KEY (`Almoxarifado_idAlmoxarifado`)
    REFERENCES `almoxarifado`.`Almoxarifado` (`idAlmoxarifado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
